async (page) => {
  const check = (condition, message) => { if (!condition) throw new Error(message); };
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  const url = 'http://127.0.0.1:5176';
  const ready = () => page.waitForFunction(() => document.querySelector('.action-dock')?.classList.contains('your-turn'));
  const result = () => page.getByRole('button', { name: '↻ 重播本局', exact: true }).waitFor({ state: 'visible', timeout: 25000 });
  const start = async (mode = 'left', fixture = 'success', seed = '42') => {
    await page.goto(url + '/tests/browser/');
    await page.getByLabel('响应模式').selectOption(fixture);
    await page.getByLabel('对战方式').selectOption(mode);
    await page.locator('.advanced summary').click();
    await page.getByLabel('随机 Seed', { exact: true }).fill(seed);
    await page.getByRole('button', { name: '开始对决', exact: true }).click();
    await page.locator('.battle-screen').waitFor();
  };
  const finishManual = async () => {
    for (let count = 0; count < 250; count++) {
      if (await page.locator('.result-screen').count()) return;
      if (await page.locator('.your-turn').count()) {
        await page.locator('[data-action]:not(:disabled)').last().click({timeout:250}).catch(() => {});
      } else if (await page.locator('#skip-battle:not(:disabled)').count()) {
        await page.locator('#skip-battle').click({timeout:250}).catch(() => {});
        await page.waitForTimeout(30);
      } else await page.waitForTimeout(80);
    }
    throw new Error('Manual match did not finish');
  };
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(url);
  await page.screenshot({ path: 'output/playwright/config-desktop.png', fullPage: true });
  check(await page.getByLabel('对战方式').inputValue() === 'left', 'Manual left must be default');
  await start();
  await ready();
  const before = await page.locator('#battle-log').textContent();
  await page.waitForTimeout(1300);
  check(await page.locator('#battle-log').textContent() === before, 'Player waiting auto-attacked');
  await page.screenshot({ path: 'output/playwright/interactive-arena.png', fullPage: true });
  await page.keyboard.press('2'); await page.keyboard.press('2'); await page.keyboard.press('3');
  check(await page.locator('#round-counter').textContent() === '02', 'Duplicate choice advanced round');
  check(await page.locator('[data-action]:not(:disabled)').count() === 0, 'Choices not locked during attack');
  await page.locator('#pause-battle').click();
  const hp = await page.locator('#hp-right').textContent(); const round = await page.locator('#round-counter').textContent();
  await page.waitForTimeout(1300);
  check(await page.locator('#hp-right').textContent() === hp && await page.locator('#round-counter').textContent() === round, 'Pause advanced attack');
  check(await page.locator('#skip-battle').isDisabled(), 'Paused manual attack can be skipped');
  await page.keyboard.press('p'); await page.locator('#skip-battle').click();
  await page.waitForFunction(() => document.querySelector('#round-counter')?.textContent === '03');
  await page.waitForFunction(() => { const button = document.querySelector('#skip-battle'); return button && !button.disabled; });
  await page.locator('#skip-battle').click(); await ready();
  check(await page.locator('[data-action="1"]').isDisabled(), 'Used skill did not cool down');
  check(await page.locator('[data-action="0"]').isEnabled(), 'Basic unavailable');
  await page.screenshot({ path: 'output/playwright/cooldown-arena.png', fullPage: true });
  await page.keyboard.press('1'); await page.locator('#skip-battle').click();
  await page.waitForFunction(() => { const button = document.querySelector('#skip-battle'); return button && !button.disabled; });
  await page.locator('#skip-battle').click(); await ready();
  check(await page.locator('[data-action="1"]').isEnabled(), 'Cooldown lasted more than one personal turn');
  await finishManual(); await result();
  await page.waitForFunction(() => !document.querySelector('#download-card')?.disabled);
  const canvas = await page.locator('canvas').evaluate(canvas => ({ width: canvas.width, height: canvas.height, avatars: canvas.dataset.missingAvatars }));
  check(canvas.width === 1200 && canvas.height === 630 && canvas.avatars === 'false', 'PNG dimensions or avatars wrong');
  check((await page.locator('.result-mode').textContent()).includes('玩家对战'), 'Result missing manual provenance');
  const log = await page.locator('#battle-log').textContent();
  const requests = await page.locator('#fixture-request-count').textContent();
  await page.screenshot({ path: 'output/playwright/result-fixture.png', fullPage: true });
  const download = page.waitForEvent('download'); await page.locator('#download-card').click();
  await (await download).saveAs('output/playwright/fixture-result.png');
  await page.locator('#replay').click();
  await page.getByLabel('速度', { exact: true }).selectOption('1800');
  await page.getByRole('button', { name: '跳过回放', exact: true }).click(); await result();
  check(await page.locator('#battle-log').textContent() === log, 'Skipped replay changed events');
  check(await page.locator('#fixture-request-count').textContent() === requests, 'Replay requested API');
  await page.locator('#replay').click(); await result();
  check(await page.locator('#battle-log').textContent() === log, 'Natural replay changed events');
  check(await page.locator('#fixture-request-count').textContent() === requests, 'Natural replay requested API');
  await page.locator('#rematch').click();
  check((await page.locator('.seed-badge').textContent()) !== 'SEED 42', 'Rematch seed unchanged');
  check((await page.locator('.mode-badge').textContent()).includes('octocat'), 'Rematch lost control side');
  await page.locator('#back-config').click(); await page.waitForTimeout(600);
  check(await page.locator('.config-screen').count() === 1 && await page.locator('.effects-canvas').count() === 0, 'Old playback survived navigation');
  await start('right'); await ready();
  check((await page.locator('#role-right').textContent()).includes('你'), 'Right control failed');
  check(await page.locator('#round-counter').textContent() === '00', 'Right initiative should await player');
  for (const width of [375,768,1024,1440]) {
    await page.setViewportSize({ width, height: 1000 });
    check(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Battle overflow at ' + width);
    if (width === 375) await page.screenshot({ path: 'output/playwright/battle-mobile.png', fullPage: true });
  }
  await page.locator('[data-action="1"]').click();
  await page.locator('#back-config').click(); await page.waitForTimeout(900);
  check(await page.locator('.config-screen').count() === 1, 'Cancelled attack mutated new screen');
  await start('auto', 'long-battle'); await page.locator('#skip-battle').click(); await result();
  check((await page.locator('.result-stats').textContent()).includes('30'), '30-turn result missing');
  await start('left', 'no-language'); await ready();
  check(await page.locator('[data-action]').count() === 1, 'No-language should offer only basic');
  await finishManual(); await result();
  await start('left', 'burst', '0');
  await page.getByLabel('速度', { exact: true }).selectOption('4000'); await ready();
  await page.keyboard.press('2');
  await page.waitForFunction(() => document.querySelector('.arena-board')?.classList.contains('critical-window'));
  await page.waitForTimeout(180);
  await page.locator('#pause-battle').click();
  await page.screenshot({ path: 'output/playwright/critical-cutin.png', fullPage: true });
  await page.locator('#pause-battle').click();
  await page.waitForFunction(() => document.querySelector('.arena-board')?.classList.contains('knockout'));
  await page.locator('#pause-battle').click();
  await page.screenshot({ path: 'output/playwright/knockout-arena.png', fullPage: true });
  await page.locator('#pause-battle').click(); await result();
  check(await page.locator('.result-stats > div').first().textContent().then(t => t.includes('1')), 'Burst did not KO');
  await page.locator('#result-config').click();
  await page.getByLabel('响应模式').selectOption('missing');
  await page.getByRole('button', { name: '开始对决', exact: true }).click();
  await page.getByRole('button', { name: '重试对决 →', exact: true }).waitFor();
  check((await page.getByRole('alert').textContent()).includes('用户不存在'), '404 missing');
  await page.getByLabel('响应模式').selectOption('network');
  await page.getByRole('button', { name: '重试对决 →', exact: true }).click();
  await page.getByRole('button', { name: '重试对决 →', exact: true }).waitFor();
  check((await page.getByRole('alert').textContent()).includes('网络连接失败'), 'Network error missing');
  await page.getByLabel('响应模式').selectOption('slow');
  await page.getByRole('button', { name: '重试对决 →', exact: true }).click(); await page.locator('#cancel-load').click();
  check(await page.locator('.config-screen').count() === 1, 'Load cancel failed');
  await start('auto', 'avatar'); await page.locator('#skip-battle').click();
  await page.waitForFunction(() => !document.querySelector('#download-card')?.disabled);
  check((await page.locator('#canvas-message').textContent()).includes('占位头像'), 'Avatar placeholder missing');
  await page.locator('#retry-card').click();
  await page.waitForFunction(() => !document.querySelector('#download-card')?.disabled);
  await start('right', 'long-name'); await ready();
  check(await page.locator('#app script').count() === 0, 'API text executed markup');
  for (const width of [375,768,1024,1440]) {
    await page.setViewportSize({ width, height: 1000 });
    check(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Long name overflow at ' + width);
  }
  await page.locator('#back-config').click();
  await page.goto(url + '/tests/browser/?motion=reduce'); await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.getByLabel('对战方式').selectOption('right');
  await page.getByRole('button', { name: '开始对决', exact: true }).click(); await ready(); await page.keyboard.press('2');
  await page.waitForFunction(() => document.querySelector('.arena-board')?.dataset.phase === 'impact');
  check(await page.locator('.effects-canvas').evaluate(el => getComputedStyle(el).visibility) === 'hidden', 'Reduced effects not disabled');
  const reducedRound = await page.locator('#round-counter').textContent();
  await page.waitForTimeout(500);
  check(await page.locator('#round-counter').textContent() === reducedRound, 'Reduced motion removed reading time');
  await page.screenshot({ path: 'output/playwright/reduced-motion.png', fullPage: true });
  await page.locator('#back-config').click();
  await page.goto(url); await page.setViewportSize({ width:375, height:812 });
  check(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Config overflow');
  await page.screenshot({ path: 'output/playwright/config-mobile.png', fullPage:true });
  await page.getByRole('button',{ name:'对战规则 ↗' }).click(); await page.keyboard.press('Escape');
  check(!(await page.getByRole('dialog').isVisible()), 'Escape failed');
  check(errors.length === 0, 'Page errors: ' + errors.join('; '));
  await page.evaluate(report => console.log('SMOKE_ACCEPTANCE ' + JSON.stringify(report)), { passed:true, manual:true, rightControl:true, cooldown:true, pause:true, replayRequests:requests, canvas, viewports:[375,768,1024,1440] });
}
